//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestBits
    {
        public int id { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<bool> imagenBits { get; set; }
    }
}
